# This file can be used with the yaml-update step
image:
  repository: public.ecr.aws/nginx/nginx
  tag: 1.29.6
  pullPolicy: IfNotPresent

replicaCount: 2

rollout:
  canary:
    steps:
      - setWeight: 20
      - pause:
          duration: 30s
      - setWeight: 50
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 30s
      - setWeight: 100

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []
