apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-demo
  namespace: kargo-demo
spec:
  replicas: 10
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
      - setWeight: 100
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.5  # Kargo will update this via values.yaml
        ports:
        - containerPort: 80
