apiVersion: v1
kind: Service
metadata:
  name: {{ include "kargo-nginx-demo.fullname" . }}
  labels:
    {{- include "kargo-nginx-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kargo-nginx-demo.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
